object Versions {
    const val coreKtx = "1.10.1"
    const val kotlinBom = "1.8.0"
    const val lifeCycleRuntime = "2.6.1"
    const val activityCompose = "1.7.2"
    const val viewModelCompose = "2.6.1"
    const val composeBom = "2022.10.00"
    const val compose = "1.4.3"
    const val composeMaterial3 = "1.1.0"
    const val constraintLayoutCompose = "1.0.1"
    const val lottie = "6.0.0"
    const val coil = "2.2.2"
    const val palette = "1.0.0"

    const val koin = "3.4.1"
    const val koinCompose = "3.4.5"
    const val room = "2.5.1"
    const val retrofit = "2.9.0"
    const val coroutines = "1.3.9"
    const val navigationCompose = "2.5.3"

    const val jUnit = "4.13.2"
    const val mockitoCore= "5.3.1"
    const val mockitoKotlin = "5.0.0"
    const val mockitoInline = "5.2.0"
    const val coroutinesTest = "1.7.1"
    const val arch = "2.2.0"
}